version: "3"
services:
  neo-cli:
    image: 340431872443.dkr.ecr.us-east-1.amazonaws.com/asteroid-neo:latest 
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "10332:10332"
    networks:
      - asteroid-neo
    volumes:
      - "Chain:/var/www/asteroid-neo/neo-cli/Chain"
networks:
  asteroid-neo:
volumes:
  Chain:
